
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analyzers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SALON = 11;
  public static final int HORARIO = 13;
  public static final int STRINGSINCOMILLA = 16;
  public static final int ASIGNAR = 14;
  public static final int STRING = 15;
  public static final int COMA = 5;
  public static final int EOF = 0;
  public static final int EDIFICIO = 10;
  public static final int TIPOESTUDIANTE = 17;
  public static final int error = 1;
  public static final int USUARIO = 8;
  public static final int ESTUDIANTE = 7;
  public static final int PUNTOCOMA = 6;
  public static final int TIPOCOLABORADOR = 18;
  public static final int ENTERO = 2;
  public static final int CATEDRATICO = 9;
  public static final int CURSO = 12;
  public static final int PARENTESISB = 4;
  public static final int PARENTESISA = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "PARENTESISA",
  "PARENTESISB",
  "COMA",
  "PUNTOCOMA",
  "ESTUDIANTE",
  "USUARIO",
  "CATEDRATICO",
  "EDIFICIO",
  "SALON",
  "CURSO",
  "HORARIO",
  "ASIGNAR",
  "STRING",
  "STRINGSINCOMILLA",
  "TIPOESTUDIANTE",
  "TIPOCOLABORADOR"
  };
}

