/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.claseMain;
import Objects.*;
import btree.LlaveEntero;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Jeffrey
 */
public class CrearHorario extends javax.swing.JFrame {

    /**
     * Creates new form CrearHorario
     */
    public CrearHorario() {
        initComponents();
        setVisible(true);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        DiajComboBox = new javax.swing.JComboBox<>();
        CursoJTextField = new javax.swing.JTextField();
        IDJTextField = new javax.swing.JTextField();
        PeriodoJTextField1 = new javax.swing.JTextField();
        IngresarjButton = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        SalonJTextField = new javax.swing.JTextField();
        CatedraticoJTextField = new javax.swing.JTextField();
        EdificioJTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 143, 157));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 143, 157));
        jLabel1.setText("Creacion de horarios");

        DiajComboBox.setBackground(new java.awt.Color(51, 51, 51));
        DiajComboBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DiajComboBox.setForeground(new java.awt.Color(255, 255, 255));
        DiajComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miercoles", "Jueves", "Viernes" }));
        DiajComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiajComboBoxMouseClicked(evt);
            }
        });

        CursoJTextField.setBackground(new java.awt.Color(51, 51, 51));
        CursoJTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CursoJTextField.setForeground(new java.awt.Color(255, 255, 255));
        CursoJTextField.setText("Codigo de curso");
        CursoJTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CursoJTextFieldMouseClicked(evt);
            }
        });

        IDJTextField.setBackground(new java.awt.Color(51, 51, 51));
        IDJTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IDJTextField.setForeground(new java.awt.Color(255, 255, 255));
        IDJTextField.setText("Codigo");
        IDJTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IDJTextFieldMouseClicked(evt);
            }
        });

        PeriodoJTextField1.setBackground(new java.awt.Color(51, 51, 51));
        PeriodoJTextField1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PeriodoJTextField1.setForeground(new java.awt.Color(255, 255, 255));
        PeriodoJTextField1.setText("Periodo");
        PeriodoJTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PeriodoJTextField1MouseClicked(evt);
            }
        });

        IngresarjButton.setBackground(new java.awt.Color(0, 143, 157));
        IngresarjButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IngresarjButton.setForeground(new java.awt.Color(255, 255, 255));
        IngresarjButton.setText("Crear horario");
        IngresarjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        IngresarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarjButtonActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(51, 51, 51));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        SalonJTextField.setBackground(new java.awt.Color(51, 51, 51));
        SalonJTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SalonJTextField.setForeground(new java.awt.Color(255, 255, 255));
        SalonJTextField.setText("Codigo del salon");
        SalonJTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalonJTextFieldMouseClicked(evt);
            }
        });

        CatedraticoJTextField.setBackground(new java.awt.Color(51, 51, 51));
        CatedraticoJTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CatedraticoJTextField.setForeground(new java.awt.Color(255, 255, 255));
        CatedraticoJTextField.setText("Codigo del catedratico");
        CatedraticoJTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CatedraticoJTextFieldMouseClicked(evt);
            }
        });

        EdificioJTextField.setBackground(new java.awt.Color(51, 51, 51));
        EdificioJTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EdificioJTextField.setForeground(new java.awt.Color(255, 255, 255));
        EdificioJTextField.setText("Codigo del edificio");
        EdificioJTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EdificioJTextFieldMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CatedraticoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 247, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(DiajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PeriodoJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CursoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SalonJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EdificioJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IngresarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(369, 369, 369))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton8)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 17, Short.MAX_VALUE)
                        .addComponent(IDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PeriodoJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DiajComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CursoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(SalonJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EdificioJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CatedraticoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(IngresarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CursoJTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CursoJTextFieldMouseClicked
        CursoJTextField.setText("");
    }//GEN-LAST:event_CursoJTextFieldMouseClicked

    private void IDJTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDJTextFieldMouseClicked
        IDJTextField.setText("");
    }//GEN-LAST:event_IDJTextFieldMouseClicked

    private void PeriodoJTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PeriodoJTextField1MouseClicked
        PeriodoJTextField1.setText("");
    }//GEN-LAST:event_PeriodoJTextField1MouseClicked

    private void IngresarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarjButtonActionPerformed
        try {
            //Estudiante
            if (IDJTextField.getText() != null && !"".equals(IDJTextField.getText())) {
                if (PeriodoJTextField1.getText() != null && !"".equals(PeriodoJTextField1.getText())) {
                    if (CursoJTextField.getText() != null && !"".equals(CursoJTextField.getText())) {
                        if (SalonJTextField.getText() != null && !"".equals(SalonJTextField.getText())) {
                            if (EdificioJTextField.getText() != null && !"".equals(EdificioJTextField.getText())) {
                                if (CatedraticoJTextField.getText() != null && !"".equals(CatedraticoJTextField.getText())) {

                                    Object edificioObject = claseMain.listaEdificios.buscarDato(EdificioJTextField.getText()).getData();
                                    if (edificioObject != null) {
                                        Edificio edificio = (Edificio) edificioObject;
                                        Object salonObject = edificio.salones.getData(SalonJTextField.getText());

                                        if (salonObject != null) {
                                            Salon salon = (Salon) salonObject;
                                            Object cursoObject = claseMain.listaCursos.buscarID(Integer.valueOf(CursoJTextField.getText())).getData();

                                            if (cursoObject != null) {
                                                Curso curso = (Curso) cursoObject;
                                                Catedratico catedratico = (Catedratico)claseMain.listaCatedraticos.buscar(Integer.valueOf(CatedraticoJTextField.getText())).getInfo();
                                                if (catedratico != null) {
                                                    Horario repetido = (Horario) claseMain.listaHorarios.search(new LlaveEntero(Integer.valueOf(IDJTextField.getText())));
                                                    if (repetido == null) {
                                                        Horario horario = new Horario(Integer.valueOf(IDJTextField.getText()), PeriodoJTextField1.getText(), DiajComboBox.getSelectedItem().toString(), curso, salon, edificio, catedratico);
                                                        claseMain.listaHorarios.insert(new LlaveEntero(Integer.valueOf(IDJTextField.getText())), horario);
                                                        JOptionPane.showMessageDialog(null, "Se creo el horario correctamente");
                                                    } else {
                                                        JOptionPane.showMessageDialog(null, "Ya existe un horario con ese codigo");
                                                    }

                                                } else {
                                                    JOptionPane.showMessageDialog(null, "No existe el catedratico ingresado");
                                                }
                                            }
                                        } else {
                                            JOptionPane.showMessageDialog(null, "No existe el salon ingresado");
                                        }
                                    } else {
                                        JOptionPane.showMessageDialog(null, "No existe el edificio ingresado");
                                    }

                                } else {
                                    JOptionPane.showMessageDialog(null, "No ingreso el codigo del edificio");
                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "No ingreso el codigo del edificio");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "No ingreso el codigo del salon");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "No ingreso el codigo del curso");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No ingreso el periodo");
                }

            } else {
                JOptionPane.showMessageDialog(null, "No ingreso el codigo");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }


    }//GEN-LAST:event_IngresarjButtonActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        mainFrame main = new mainFrame();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void SalonJTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalonJTextFieldMouseClicked
        SalonJTextField.setText("");
    }//GEN-LAST:event_SalonJTextFieldMouseClicked

    private void CatedraticoJTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CatedraticoJTextFieldMouseClicked
        CatedraticoJTextField.setText("");
    }//GEN-LAST:event_CatedraticoJTextFieldMouseClicked

    private void EdificioJTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EdificioJTextFieldMouseClicked
        EdificioJTextField.setText("");
    }//GEN-LAST:event_EdificioJTextFieldMouseClicked

    private void DiajComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiajComboBoxMouseClicked

    }//GEN-LAST:event_DiajComboBoxMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearHorario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CatedraticoJTextField;
    private javax.swing.JTextField CursoJTextField;
    private javax.swing.JComboBox<String> DiajComboBox;
    private javax.swing.JTextField EdificioJTextField;
    private javax.swing.JTextField IDJTextField;
    private javax.swing.JButton IngresarjButton;
    private javax.swing.JTextField PeriodoJTextField1;
    private javax.swing.JTextField SalonJTextField;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
